use proptest::prelude::*;
use regex::Regex;

// ---------------------------------------------------------------------------
// Constantes espelhadas de src/constants.rs — sem importar a crate em testes
// ---------------------------------------------------------------------------

const MAX_MEMORY_NAME_LEN: usize = 80;
const MAX_MEMORY_BODY_LEN: usize = 512_000;
const NAME_SLUG_REGEX: &str = r"^[a-z][a-z0-9-]{0,78}[a-z0-9]$|^[a-z0-9]$";

// Number of proptest cases. In CI it can be reduced via PROPTEST_CASES=32.
fn proptest_config() -> ProptestConfig {
    let cases = std::env::var("PROPTEST_CASES")
        .ok()
        .and_then(|v| v.parse::<u32>().ok())
        .unwrap_or(256);
    ProptestConfig::with_cases(cases)
}

// ---------------------------------------------------------------------------
// Suite 5 — Property-based tests
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(proptest_config())]

    /// Any string generated by the kebab-case regex must match NAME_SLUG_REGEX.
    #[test]
    fn name_slug_regex_accepts_kebab_case(
        name in "[a-z][a-z0-9-]{0,78}[a-z0-9]"
    ) {
        let re = Regex::new(NAME_SLUG_REGEX).unwrap();
        prop_assert!(
            re.is_match(&name),
            "Nome kebab valido rejeitado: {:?}",
            name
        );
    }

    /// Single lowercase char must match (variant `^[a-z0-9]$`).
    #[test]
    fn name_slug_regex_accepts_single_lowercase_char(
        c in "[a-z0-9]"
    ) {
        let re = Regex::new(NAME_SLUG_REGEX).unwrap();
        prop_assert!(
            re.is_match(&c),
            "Char unico valido rejeitado: {:?}",
            c
        );
    }

    /// Uppercase letters must always be rejected by the regex.
    #[test]
    fn name_slug_regex_rejects_uppercase(
        upper in "[A-Z]{1,5}[a-z0-9-]{0,10}"
    ) {
        let re = Regex::new(NAME_SLUG_REGEX).unwrap();
        prop_assert!(
            !re.is_match(&upper),
            "Uppercase incorretamente aceito: {:?}",
            upper
        );
    }

    /// Underscore must never be accepted by the regex.
    #[test]
    fn name_slug_regex_rejects_underscore(
        prefix in "[a-z]{1,10}",
        suffix in "[a-z]{1,10}"
    ) {
        let nome_com_underscore = format!("{prefix}_{suffix}");
        let re = Regex::new(NAME_SLUG_REGEX).unwrap();
        prop_assert!(
            !re.is_match(&nome_com_underscore),
            "Underscore incorretamente aceito: {:?}",
            nome_com_underscore
        );
    }

    /// Strings containing whitespace must be rejected.
    #[test]
    fn name_slug_regex_rejects_space(
        a in "[a-z]{1,10}",
        b in "[a-z]{1,10}"
    ) {
        let nome_com_espaco = format!("{a} {b}");
        let re = Regex::new(NAME_SLUG_REGEX).unwrap();
        prop_assert!(
            !re.is_match(&nome_com_espaco),
            "Espaco incorretamente aceito: {:?}",
            nome_com_espaco
        );
    }

    /// Any ASCII string longer than MAX_MEMORY_BODY_LEN bytes must
    /// have a length above the limit — boundary invariant.
    #[test]
    fn body_length_boundary_unicode_above_limit(
        extra in "[\\p{L}]{1,500}"
    ) {
        // Gera um body com pelo menos MAX_MEMORY_BODY_LEN + len(extra) bytes.
        let padding: String = "a".repeat(MAX_MEMORY_BODY_LEN);
        let body = format!("{padding}{extra}");
        prop_assert!(
            body.len() > MAX_MEMORY_BODY_LEN,
            "Body deveria exceder limite mas tem {} bytes",
            body.len()
        );
    }

    /// ASCII body up to MAX_MEMORY_BODY_LEN bytes must be <= the limit.
    #[test]
    fn body_length_boundary_unicode_no_limite(
        chars in "[A-Za-z0-9]{1,4096}"
    ) {
        let truncated: String = chars.chars().take(MAX_MEMORY_BODY_LEN).collect();
        prop_assert!(
            truncated.len() <= MAX_MEMORY_BODY_LEN,
            "Truncado deveria ser <= {} mas tem {} bytes",
            MAX_MEMORY_BODY_LEN,
            truncated.len()
        );
    }

    /// Name with length between 1 and MAX_MEMORY_NAME_LEN bytes and kebab format
    /// must be considered valid by the length invariant.
    #[test]
    fn name_length_valid_within_limit(
        name in "[a-z][a-z0-9-]{0,78}[a-z0-9]"
    ) {
        prop_assert!(
            !name.is_empty() && name.len() <= MAX_MEMORY_NAME_LEN,
            "Nome {:?} tem comprimento {} fora do range [1, {}]",
            name,
            name.len(),
            MAX_MEMORY_NAME_LEN
        );
    }

    /// BLAKE3 is deterministic: the same input produces the same hash across distinct calls.
    #[test]
    fn embedding_determinism_blake3_mesmo_hash_para_mesmo_input(
        body in "[\\p{L}\\p{N} .,!?]{1,1000}"
    ) {
        let hash_a = blake3::hash(body.as_bytes());
        let hash_b = blake3::hash(body.as_bytes());
        prop_assert_eq!(
            hash_a,
            hash_b,
            "BLAKE3 nao e determinístico para input {:?}",
            &body[..body.len().min(40)]
        );
    }

    /// BLAKE3 hashes of distinct inputs must differ (collision is extremely
    /// unlikely — this property tests practical anti-collision).
    #[test]
    fn embedding_determinism_blake3_inputs_distintos_hashes_distintos(
        a in "[a-z]{10,50}",
        b in "[A-Z]{10,50}"
    ) {
        // a is lowercase, b is uppercase — guaranteed to be distinct.
        let hash_a = blake3::hash(a.as_bytes());
        let hash_b = blake3::hash(b.as_bytes());
        prop_assert_ne!(
            hash_a,
            hash_b,
            "Colisão de BLAKE3 inesperada entre {:?} e {:?}",
            a,
            b
        );
    }

    /// JSON serialization of a simple object with name + description + body
    /// must be round-trippable: deserializing the serialized JSON returns the
    /// same original values.
    #[test]
    fn json_round_trip_nome_descricao_body(
        name in "[a-z][a-z0-9-]{0,30}[a-z0-9]",
        description in "[\\p{L}\\p{N} .,!?]{1,200}",
        body in "[\\p{L}\\p{N} .,!?\n]{1,500}"
    ) {
        #[derive(serde::Serialize, serde::Deserialize, Debug, PartialEq)]
        struct Payload {
            name: String,
            description: String,
            body: String,
        }

        let original = Payload {
            name: name.clone(),
            description: description.clone(),
            body: body.clone(),
        };

        let json = serde_json::to_string(&original).unwrap();
        let restored: Payload = serde_json::from_str(&json).unwrap();

        prop_assert_eq!(
            &original,
            &restored,
            "Round-trip JSON failed para nome={:?}",
            name
        );
    }
}

// ---------------------------------------------------------------------------
// Complementary unit tests (non-proptest)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod unit_tests {
    use super::*;

    #[test]
    fn name_slug_regex_accepts_canonical_examples() {
        let re = Regex::new(NAME_SLUG_REGEX).unwrap();
        let validos = [
            "a",
            "z",
            "0",
            "abc",
            "my-memory",
            "projeto-rust-2026",
            "a0",
            "a-b-c",
            // 80 chars exatos
            &"a".repeat(79)
                .as_str()
                .chars()
                .chain(std::iter::once('b'))
                .collect::<String>(),
        ];
        for nome in &validos {
            assert!(re.is_match(nome), "Nome canonico rejeitado: {nome:?}");
        }
    }

    #[test]
    fn name_slug_regex_rejects_invalid_examples() {
        let re = Regex::new(NAME_SLUG_REGEX).unwrap();
        let invalidos = [
            "",
            "A",
            "My-Memory",
            "my_memory",
            "my memory",
            "-starts-with-dash",
            "ends-with-dash-",
            "__reserved",
        ];
        for nome in &invalidos {
            assert!(
                !re.is_match(nome),
                "Nome invalido incorretamente aceito: {nome:?}"
            );
        }
    }

    #[test]
    fn blake3_hash_bytes_tem_32_bytes() {
        let h = blake3::hash(b"sqlite-graphrag");
        assert_eq!(h.as_bytes().len(), 32);
    }

    #[test]
    fn body_at_exact_limit_accepted() {
        let body: String = "x".repeat(MAX_MEMORY_BODY_LEN);
        assert_eq!(body.len(), MAX_MEMORY_BODY_LEN);
    }

    #[test]
    fn body_one_above_limit_detected() {
        let body: String = "x".repeat(MAX_MEMORY_BODY_LEN + 1);
        assert!(body.len() > MAX_MEMORY_BODY_LEN);
    }
}
