-- v1.0.76: vec tables no longer created. The V013 migration drops them
-- for users migrating from v1.0.74 or earlier. This file is intentionally
-- a no-op (refinery refuses to run a migration whose file content does
-- not match the recorded checksum, so we cannot remove the file).
--
-- IMPORTANT UPGRADE NOTE: users with a v1.0.74 database who upgrade to
-- v1.0.76 will see exit code 20 (\"migration checksum mismatch\") because
-- the recorded V002 checksum differs from the new (empty) file. The
-- remediation is to delete the database file and re-run `init`, OR to
-- run `sqlite-graphrag migrate --rehash` (planned for v1.0.77) which
-- rewrites the recorded checksum to match the new file content.
SELECT 1;
